### ISSUE TITLE
[NeatURL] brainstorm: same-origin/same-domain global switch dynamic whitelist

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#127]
Hi @Smile4ever, it's me... again :smile: 

This is not a request/issue, at least not yet... lets say it a brainstorming.

What do you think about global switch/setting saying: Do not block parameters on same-domain/same-origin.
Lets focus now just to same domain and not subdomain, which is more complicated (another brainstorm if you find the suggestion useful).

So, when I navigate to some domain (lets say source-domain), when I click the link which opens a new page (lets say destination-domain)... essentially same-domain/same-origin,  and if the destination-domain is the same as the source-domain it will skip the parameters stripping even if those parameters are in "blocked parameters" list.
Since we are still on same domain, we can say that there is no privacy/tracking issue (the page already knows me).
This way we can accomplish more relaxed "blocked parameters" list, with much much less of false-positives that could lead to a breakages.

What is your opinion?

Cheers

**Comment by Smile4ever** [comment]
_Note: Different pages can have different URL parameters that need to be stripped away. Not everyone is cleaning their URLs for privacy, there are people that like clean URLs a lot (since it's easier to read and share, for example)._

I see a minor use case, but I think this will lead to people complaining that their URL parameters are not cleaned. (and the added complexity makes Neat URL harder to maintain)

You mean something like
* You navigate from https://tweakers.net/ to https://tweakers.net/productreview/187157/sony-xperia-xz2-compact-zwart.html?param=test

when you added param@tweakers.net to the blocked parameters, param would not be cleaned.

I fail to see how that improves user experience. Do you have a concrete use case where there would be a benefit? An example would help to demonstrate the usefulnes for sure.

**Comment by crssi** [comment]
Sorry for being MIA and in the next week or so I will also not be active as usual.

> I see a minor use case, but I think this will lead to people complaining that their URL parameters are not cleaned. (and the added complexity makes Neat URL harder to maintain)

I see. But I am saying this should be an optional switch.

> You mean something like
    You navigate from https://tweakers.net/ to https://tweakers.net/productreview/187157/sony-xperia-xz2-compact-zwart.html?param=test
when you added param@tweakers.net to the blocked parameters, param would not be cleaned.

Yes.

> Do you have a concrete use case where there would be a benefit? An example would help to demonstrate the usefulnes for sure.

Sure, will be paying attention in the next month and get back.
If you are OK, I will close this one and reopen when I have more feedback.

Cheers
