### ISSUE TITLE
Middle Click On Page Closes Tab: permission: Display notifications to you

### ISSUE THREAD

**Issue by atomGit** [Smile4ever/firefoxaddons#17]
hi - could you explain what the permission "Display notifications to you" is for?

this whole permissions thing rolling out for FF add-ons is interesting, but i think it's going to raise a lot of questions like this also :)

**Comment by Smile4ever** [comment]
Sure.

From the changelog (1.0.0):
Add Escape shortcut to enable allowscrolling once on a page (might be changed in a future release - this feature is documented in the README) - requires new permission notifications

The notifications permission is used to display a notification when you press Escape, so you know autoscrolling is enabled on that page. Otherwise the user doesn't have an indication on what's going on.
