### ISSUE TITLE
[Neat URL] What means "keys are now case sensitive" in 2.1.2?

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#45]
Does it means that when for example we have parameter in settings `utm_source` it wont be catched if there will be parametes in URL like `UTM_source`?

**Comment by Smile4ever** [comment]
That's indeed the case. UTM_source will work if you add the parameter UTM_source. It will not work when you only have utm_source defined. I do not have seen UTM_source or UTM_SOURCE parameters yet.

The only thing I did was remove one .toLowerCase since it didn't allow mixed case parameters which are used on addons.mozilla.org (for example, isDefaultBrowser@addons.mozilla.org).

I do think things like UTM_source didn't work in previous versions either. If you come across a UTM_source occurence, please let me know where and I'll adapt the code.

**Comment by crssi** [comment]
Understood. Thank you
