### ISSUE TITLE
[Neat URL] Overly-aggressive URL cleaning breaks websites; hard to diagnose due to logging ineffective

### ISSUE THREAD

**Issue by ronjouch** [Smile4ever/firefoxaddons#52]
Open https://vividness.live/2015/10/12/developing-ethical-social-and-cognitive-competence/

- Expected: site loads fully.
- Actual:
    - Without Neat URL, site loads fully.
    - With Neat URL, site loads partially, due to several requests to css/js resources ending up failing as `400 Bad Request`:  
![neaturl-breaking-website-fs8](https://user-images.githubusercontent.com/522085/31319230-a75a2d18-ac2d-11e7-8acc-2d493ad02cf2.png)

I tried to `Enable Logging` to try to get an idea of which URL parameter might be culprit, but nothing is logged (I think this logging feature is new, maybe it's buggy and sometimes fails to log?). Also, the requests look identical, and quickly looking at them I failed at finding a parameter that is part of NeatURL's blocked parameters set. HALP!

Second use case: https://video.vice.com/fr_ca/video/a-la-rencontre-des-jeunes-skateuses-dafghanistan/59c590a1b316d26a192b11f6 . With NeatURL, video fails to load.

Neat URL 3.0.0 with default `Blocked parameters` options, Firefox 58.0a1 (2017-10-08)

---

Aside: I had to go look at `options.js` on GitHub to grab the default settings; would it make sense to have a `Reset default set of blocked parameters` button to let users do this easily? **EDIT** on second thoughts, that looks like a good way for users to shoot themselves in the foot and lose their filters. Maybe a `Copy to clipboard default set of blocked parameters`, then? (In order to let users do the edition/merging themselves).

**Comment by ronjouch** [comment]
Ah, looks like a duplicate of #49 #50, closing.

**Comment by ronjouch** [comment]
Re-opening, as #50 was closed by its author

**Comment by gwarser** [comment]
>I tried to Enable Logging to try to get an idea of which URL parameter might be culprit, but nothing is logged

Look in "Browser console" (ctrl+shift+j), not in "Web console" (ctrl+shift+k)

**Comment by ronjouch** [comment]
> *Look in "Browser console" (ctrl+shift+j), not in "Web console" (ctrl+shift+k)*

@gwarser thanks! Didn't know "Browser Console" was a thing when I read it in the option sub-title 😄.

**Comment by Smile4ever** [comment]
What I did is the following:
* I fixed a few issues with the usage of the URL() constructor (used since 3.0.0)
* I set the default type for content filtering to main_frame. This means only visible requests will be cleaned (like clicking a link, not a page fetching a resource). The exception to this rule is the anti-tracking list which doesn't work on main_frame requests, but works on all other types of requests. Having only visible URLs cleaned makes the change less likely to break the page. If you want the old behaviour back, you can go to the options and add all of the request types listed on this page:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType

These changes are available in Neat URL 3.1.0.

**Comment by crssi** [comment]
@Smile4ever  did the old behavior covered all request types listed on that link, or just some of those?

**Comment by Smile4ever** [comment]
@crssi It did cover all requests.

**Comment by ronjouch** [comment]
@Smile4ever fix tested and confirmed, thanks for the fast response and continued work on NeatURL 🙂.
