### ISSUE TITLE
[Neat URL] bug?

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#77]
"Neat URL (type script): https://tch441957.tch.quora.com/up/chan41-8888/updates?&callback=jsonp8eb63c3c203b40308e9c9facba6240d5&min_seq=4336174652&channel=main-w-dep3501-3610276815995925325&hash=3999452785341597215&_=1508599193321 has been changed to https://tch441957.tch.quora.com/up/chan41-8888/updates?callback=jsonp8eb63c3c203b40308e9c9facba6240d5&min_seq=4336174652&channel=main-w-dep3501-3610276815995925325&hash=3999452785341597215&_=1508599193321"

See `/updates?&callback=` has been changed to `/updates?callback=` which should not happen.

I don't know what have been changed from 2.1.2 version on, maybe using some other API?
In that case that API obviously have a lot of problems. The same goes with double quote problem.

From my point of view, versions newer than 2.1.2 are a big step back because of that. :(
Should there any bug to be reported to bugzilla?

**Comment by Smile4ever** [comment]
I'm using the URL constructor since 3.0 which seemed nice, but I'm not so sure anymore now. https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

You might want to report a bug on Bugzilla where you outline the problems with the URL constructor as implemented by Firefox.

I'll be duping this bug to #73

**Comment by crssi** [comment]
I would be glad to report to Bugzilla, since obviously this is the only way to make this API work, but my knowledge here is to limited. :(
