### ISSUE TITLE
Two simple questions

### ISSUE THREAD

**Issue by Decopi** [Smile4ever/firefoxaddons#99]
Hi, two simple questions:

1) Is it possible to add to NeatURL other functions like "redirecting", "skipping" etc?
If not, why do we need two add-ons for that? Please, does anybody know an add-on "all-in-one", tracking cleaning & redirecting/skipping urls?

2) Some antitracking/skip/redirect add-ons are around or even less than 10 KiB size, with minimum system performance impact. Does add-on size/performance depend on quantity of rules/blocking or redirecting capabilities?

Thank you!

**Comment by Smile4ever** [comment]
1. It's possible, but I feel Neat URL should not include such a function since it will complicate the code further, introducing new bugs. "Simple" solutions are not the best solutions; that's why multiple addons exist for different purposes.

2. Yes, but I don't know how noticeable this performance impact is. I don't know how many parameters you have in Neat URL? With 100 parameters I still don't notice a performance impact.

**Comment by Decopi** [comment]
@Smile4ever thanks for your answers!

From user point of view, more add-ons implies more RAM used, and also more possible incompatibilities with other add-ons etc. Not to mention that less add-ons implies fast way to solve bugs, support etc.
I perfectly understand that two totally different add-ons (say a video-downloader and an email-checker), it makes no sense to unify. But here we're talking about URLs. And ok, I am not a developer, you're right, some times is difficult to build add-ons, supporting them etc. But in terms of pure function, to clean URLs implies by logic to clean tracking, redirecting, skipping etc.

But I don't blame you!
In years I haven't seen one URLs add-on unifying functions (did you?).

Regarding question 2, I was not talking specifically about NeatURL. I saw other similar add-ons with almost 500 KiB, and impacting system resources. In this context I wanted to understand if this happens because of bad developers, bad codes etc... or because excellent blocking capabilities of this add-ons.
Let me make an analogy with ad-blockers:  Some of them are RAM killers, heavies, with tons of KiB etc. And they justify this by saying that they "block all". It happens that there is not such thing like "blocking all". Also, some times we don't need to block everything. And worst, people in Africa, South America, India etc, doesn't have 80% of the ads or trackers in Europe, USA etc. So, I used same logic with URLs cleaners, and wanted to know if justifies or not the KiB size, RAM, quantity of rules etc.

Thank you again!

**Comment by Smile4ever** [comment]
> From user point of view, more add-ons implies more RAM used

That's not always the case. Many small addons can be more efficient than one addon that does a lot of things. This is because of missing performance or memory optimalisation, or a lack of developer time.

Yes, the memory overhead will be higher, but that will never be much (a few megabytes). With overhead I mean an addon that does nothing takes some memory already.

> But here we're talking about URLs. And ok, I am not a developer, you're right, some times is difficult to build add-ons, supporting them etc. But in terms of pure function, to clean URLs implies by logic to clean tracking, redirecting, skipping etc.

I understand, but combining them has some disadvantages as well:
- It might not be clear what the addon is capable of to the user
- The description of an addon becomes "I can do everything with URLs" which isn't true
- Bugs might take a longer time to fix, since the code base is larger ("bloated") and the developer needs to find the cause in a larger haystack.
- Not all functionalities will be tested properly before a new release happens, breaking some features when time goes by.

At the other side you have small addons that do one thing, and do it well:
* They contain the minimal code to make it work.
* They contain some code around them to make them awesome to use, like an options screen, and some notifications to inform or warn the user.

> In years I haven't seen one URLs add-on unifying functions (did you?).

I haven't come across one myself either.

> Regarding question 2, I was not talking specifically about NeatURL. I saw other similar add-ons with almost 500 KiB, and impacting system resources. In this context I wanted to understand if this happens because of bad developers, bad codes etc... or because excellent blocking capabilities of this add-ons.

Performance / memory issues can have a lot of causes:
* Bad code that "leaks" memory (it does not release memory that's not in use anymore)
* Bad code design, impacting performance
* Too many features that aren't used by the user, but which are still activated
* Good code design, but large amounts of data (like adblocking, it's not that easy)

The line between features and performance is a difficult line to walk on. Include too few features and your users will ask to add new features; include too many features and your users will complain about the speed and memory usage.

**Comment by Decopi** [comment]
@smile4ever thank you for your answers, and again thank you for your add-on.
